server:
  port: 8081
  error:
    whitelabel:
      enabled: false

spring:
  mvc:
    favicon:
      enabled: false
  datasource:
    url: jdbc:mysql://127.0.0.1:13306/drug?useUnicode=true&characterEncoding=utf-8&serverTimezone=PRC&useSSL=false
    username: root
    password: 159753hlongde
  jpa:
    show-sql: false
  jackson:
    default-property-inclusion: non_null